name: build

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies (Windows)
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            make
            mingw-w64-x86_64-clang
        if: matrix.os == 'windows-latest'

      - name: Make (Windows)
        shell: msys2 {0}
        run: |
          make CPU=m68k SYNTAX=mot -j3
          strip vasmm68k_mot.exe
          mkdir build
          mv vasmm68k_mot.exe build
        if: matrix.os == 'windows-latest'

      - name: Make (non-Windows)
        run: |
          make CPU=m68k SYNTAX=mot -j3
          strip vasmm68k_mot
          mkdir build
          mv vasmm68k_mot build
        if: matrix.os != 'windows-latest'

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}
          path: build
